[theme]
base = "light"
primaryColor = "#12529A"
backgroundColor = "#F3F7FC"
secondaryBackgroundColor = "#EAF1F9"
textColor = "#10243E"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
